In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [47]:
df=pd.read_csv("/content/flight_delays.csv")

In [ ]:
df

,FlightID,Airline,FlightNumber,Origin,Destination,ScheduledDeparture,ActualDeparture,ScheduledArrival,ActualArrival,DelayMinutes,DelayReason,Cancelled,Diverted,AircraftType,TailNumber,Distance
0,1,United,4558.0,ORD,MIA,2024-09-01 08:11,2024-09-01 08:30,2024-09-01 12:11,2024-09-01 12:19,8.0,Weather,True,False,Boeing 737,N71066,1031.0
1,2,Delta,8021.0,LAX,MIA,2024-09-01 10:25,2024-09-01 10:41,2024-09-01 13:25,2024-09-01 13:27,2.0,Air Traffic Control,True,True,Airbus A320,N22657,1006.0
2,3,Southwest,7520.0,DFW,SFO,2024-09-01 16:53,2024-09-01 17:05,2024-09-01 17:53,2024-09-01 18:07,14.0,Weather,True,True,Boeing 737,N95611,2980.0
3,4,Delta,2046.0,ORD,BOS,2024-09-01 14:44,2024-09-01 15:04,2024-09-01 18:44,2024-09-01 18:34,-10.0,NaN,False,False,Boeing 777,N90029,1408.0
4,5,Delta,6049.0,LAX,SEA,2024-09-01 01:51,2024-09-01 02:08,2024-09-01 05:51,2024-09-01 06:15,24.0,Air Traffic Control,False,True,Boeing 737,N27417,2298.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475401,1475402,Southwest,3798.0,ATL,BOS,2024-09-01 12:53,2024-09-01 13:22,2024-09-01 17:53,2024-09-01 18:10,17.0,Weather,True,True,Airbus A320,N43209,1978.0
1475402,1475403,United,9309.0,DFW,JFK,2024-09-01 13:31,2024-09-01 13:50,2024-09-01 14:31,2024-09-01 14:55,24.0,Air Traffic Control,True,False,Airbus A320,N85174,1906.0
1475403,1475404,American Airlines,6946.0,ORD,JFK,2024-09-01 04:07,2024-09-01 04:18,2024-09-01 06:07,2024-09-01 06:08,1.0,Weather,True,True,Boeing 737,N93376,1985.0
1475404,1475405,Delta,5369.0,DFW,SEA,2024-09-01 05:56,2024-09-01 06:18,2024-09-01 08:56,2024-09-01 09:13,17.0,Air Traffic Control,False,True,Airbus A320,N58768,951.0
1475405,1475406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.head()

,FlightID,Airline,FlightNumber,Origin,Destination,ScheduledDeparture,ActualDeparture,ScheduledArrival,ActualArrival,DelayMinutes,DelayReason,Cancelled,Diverted,AircraftType,TailNumber,Distance
0,1,United,4558.0,ORD,MIA,2024-09-01 08:11,2024-09-01 08:30,2024-09-01 12:11,2024-09-01 12:19,8.0,Weather,True,False,Boeing 737,N71066,1031.0
1,2,Delta,8021.0,LAX,MIA,2024-09-01 10:25,2024-09-01 10:41,2024-09-01 13:25,2024-09-01 13:27,2.0,Air Traffic Control,True,True,Airbus A320,N22657,1006.0
2,3,Southwest,7520.0,DFW,SFO,2024-09-01 16:53,2024-09-01 17:05,2024-09-01 17:53,2024-09-01 18:07,14.0,Weather,True,True,Boeing 737,N95611,2980.0
3,4,Delta,2046.0,ORD,BOS,2024-09-01 14:44,2024-09-01 15:04,2024-09-01 18:44,2024-09-01 18:34,-10.0,NaN,False,False,Boeing 777,N90029,1408.0
4,5,Delta,6049.0,LAX,SEA,2024-09-01 01:51,2024-09-01 02:08,2024-09-01 05:51,2024-09-01 06:15,24.0,Air Traffic Control,False,True,Boeing 737,N27417,2298.0

In [ ]:
df.tail()

,FlightID,Airline,FlightNumber,Origin,Destination,ScheduledDeparture,ActualDeparture,ScheduledArrival,ActualArrival,DelayMinutes,DelayReason,Cancelled,Diverted,AircraftType,TailNumber,Distance
1475401,1475402,Southwest,3798.0,ATL,BOS,2024-09-01 12:53,2024-09-01 13:22,2024-09-01 17:53,2024-09-01 18:10,17.0,Weather,True,True,Airbus A320,N43209,1978.0
1475402,1475403,United,9309.0,DFW,JFK,2024-09-01 13:31,2024-09-01 13:50,2024-09-01 14:31,2024-09-01 14:55,24.0,Air Traffic Control,True,False,Airbus A320,N85174,1906.0
1475403,1475404,American Airlines,6946.0,ORD,JFK,2024-09-01 04:07,2024-09-01 04:18,2024-09-01 06:07,2024-09-01 06:08,1.0,Weather,True,True,Boeing 737,N93376,1985.0
1475404,1475405,Delta,5369.0,DFW,SEA,2024-09-01 05:56,2024-09-01 06:18,2024-09-01 08:56,2024-09-01 09:13,17.0,Air Traffic Control,False,True,Airbus A320,N58768,951.0
1475405,1475406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(1475406, 16)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475406 entries, 0 to 1475405
Data columns (total 16 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   FlightID            1475406 non-null  int64
 1   Airline             1475405 non-null  object
 2   FlightNumber        1475405 non-null  float64
 3   Origin              1475405 non-null  object
 4   Destination         1475405 non-null  object
 5   ScheduledDeparture  1475405 non-null  object
 6   ActualDeparture     1475405 non-null  object
 7   ScheduledArrival    1475405 non-null  object
 8   ActualArrival       1475405 non-null  object
 9   DelayMinutes        1475405 non-null  float64
 10  DelayReason         1079666 non-null  object
 11  Cancelled           1475405 non-null  object
 12  Diverted            1475405 non-null  object
 13  AircraftType        1475405 non-null  object
 14  TailNumber          1475405 non-null  object
 15  Distance            1475405 non-null  float64
dtypes: float64(3), int64(1), object(12)
memory usage: 180.1+ MB

In [ ]:
df.describe()

           FlightID  FlightNumber  DelayMinutes      Distance
count  1.475406e+06  1.475405e+06  1.475405e+06  1.475405e+06
mean   7.377035e+05  5.001617e+03  1.000053e+01  1.550148e+03
std    4.259132e+05  2.885982e+03  1.182949e+01  8.368068e+02
min    1.000000e+00  1.000000e+00 -1.000000e+01  1.000000e+02
25%    3.688522e+05  2.503000e+03  0.000000e+00  8.250000e+02
50%    7.377035e+05  5.003000e+03  1.000000e+01  1.551000e+03
75%    1.106555e+06  7.500000e+03  2.000000e+01  2.275000e+03
max    1.475406e+06  9.999000e+03  3.000000e+01  3.000000e+03

In [ ]:
print(df.columns)

Index(['FlightID', 'Airline', 'FlightNumber', 'Origin', 'Destination',
       'ScheduledDeparture', 'ActualDeparture', 'ScheduledArrival',
       'ActualArrival', 'DelayMinutes', 'DelayReason', 'Cancelled', 'Diverted',
       'AircraftType', 'TailNumber', 'Distance'],
      dtype='object')

In [ ]:
df.dtypes

FlightID                int64
Airline                object
FlightNumber          float64
Origin                 object
Destination            object
ScheduledDeparture     object
ActualDeparture        object
ScheduledArrival       object
ActualArrival          object
DelayMinutes          float64
DelayReason            object
Cancelled              object
Diverted               object
AircraftType           object
TailNumber             object
Distance              float64
dtype: object

In [ ]:
df.isnull().sum()

FlightID                   0
Airline                    1
FlightNumber               1
Origin                     1
Destination                1
ScheduledDeparture         1
ActualDeparture            1
ScheduledArrival           1
ActualArrival              1
DelayMinutes               1
DelayReason           395740
Cancelled                  1
Diverted                   1
AircraftType               1
TailNumber                 1
Distance                   1
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
print(df['DelayReason'].value_counts(dropna=False))

DelayReason
NaN                    395740
Weather                360203
Air Traffic Control    359768
Maintenance            359695
Name: count, dtype: int64

In [ ]:
print(df[['DelayReason', 'Cancelled', 'Diverted']].head(20))

            DelayReason Cancelled Diverted
0               Weather      True    False
1   Air Traffic Control      True     True
2               Weather      True     True
3                   NaN     False    False
4   Air Traffic Control     False     True
5                   NaN     False    False
6               Weather     False     True
7               Weather     False     True
8               Weather     False    False
9           Maintenance      True    False
10                  NaN      True     True
11              Weather     False    False
12          Maintenance     False    False
13  Air Traffic Control     False     True
14              Weather     False     True
15                  NaN     False    False
16              Weather     False    False
17                  NaN      True    False
18              Weather      True     True
19  Air Traffic Control      True     True

In [ ]:
df['DelayReason'] = df['DelayReason'].fillna('No Delay')

In [ ]:
df.isnull().sum()

FlightID              0
Airline               1
FlightNumber          1
Origin                1
Destination           1
ScheduledDeparture    1
ActualDeparture       1
ScheduledArrival      1
ActualArrival         1
DelayMinutes          1
DelayReason           0
Cancelled             1
Diverted              1
AircraftType          1
TailNumber            1
Distance              1
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

FlightID              0
Airline               0
FlightNumber          0
Origin                0
Destination           0
ScheduledDeparture    0
ActualDeparture       0
ScheduledArrival      0
ActualArrival         0
DelayMinutes          0
DelayReason           0
Cancelled             0
Diverted              0
AircraftType          0
TailNumber            0
Distance              0
dtype: int64

#Create the Target Variable
Since this is a Flight Delay Prediction project, create the target from DelayMinutes.

In [ ]:
df['Delayed'] = (df['DelayMinutes'] > 15).astype(int)

In [ ]:
df['Delayed'].value_counts()

Delayed
0    935741
1    539664
Name: count, dtype: int64

In [ ]:
df.drop(columns=[
    'FlightID',
    'FlightNumber',
    'TailNumber',
    'DelayMinutes'
], inplace=True)

In [ ]:
print(df.columns)
print(df.shape)

Index(['Airline', 'Origin', 'Destination', 'ScheduledDeparture',
       'ActualDeparture', 'ScheduledArrival', 'ActualArrival', 'DelayReason',
       'Cancelled', 'Diverted', 'AircraftType', 'Distance', 'Delayed'],
      dtype='object')
(1475405, 13)

In [ ]:
print(df.dtypes)

Airline                object
Origin                 object
Destination            object
ScheduledDeparture     object
ActualDeparture        object
ScheduledArrival       object
ActualArrival          object
DelayReason            object
Cancelled              object
Diverted               object
AircraftType           object
Distance              float64
Delayed                 int64
dtype: object

In [ ]:
import pandas as pd

df['ScheduledDeparture'] = pd.to_datetime(df['ScheduledDeparture'], errors='coerce')
df['ActualDeparture'] = pd.to_datetime(df['ActualDeparture'], errors='coerce')
df['ScheduledArrival'] = pd.to_datetime(df['ScheduledArrival'], errors='coerce')
df['ActualArrival'] = pd.to_datetime(df['ActualArrival'], errors='coerce')

In [ ]:
df[['ScheduledDeparture','ActualDeparture','ScheduledArrival','ActualArrival']].isnull().sum()

ScheduledDeparture    0
ActualDeparture       0
ScheduledArrival      0
ActualArrival         0
dtype: int64

In [ ]:
df['ScheduledDepartureHour'] = df['ScheduledDeparture'].dt.hour
df['ActualDepartureHour'] = df['ActualDeparture'].dt.hour

df['ScheduledArrivalHour'] = df['ScheduledArrival'].dt.hour
df['ActualArrivalHour'] = df['ActualArrival'].dt.hour

In [48]:
df.drop(columns=[
    'ScheduledDeparture',
    'ActualDeparture',
    'ScheduledArrival',
    'ActualArrival'
], inplace=True)

In [ ]:
print(df.columns)

Index(['Airline', 'Origin', 'Destination', 'DelayReason', 'Cancelled',
       'Diverted', 'AircraftType', 'Distance', 'Delayed',
       'ScheduledDepartureHour', 'ActualDepartureHour', 'ScheduledArrivalHour',
       'ActualArrivalHour'],
      dtype='object')

In [ ]:
print(df.dtypes)

Airline                    object
Origin                     object
Destination                object
DelayReason                object
Cancelled                  object
Diverted                   object
AircraftType               object
Distance                  float64
Delayed                     int64
ScheduledDepartureHour      int32
ActualDepartureHour         int32
ScheduledArrivalHour        int32
ActualArrivalHour           int32
dtype: object

In [ ]:
print(df['Cancelled'].unique())
print(df['Diverted'].unique())

[1 0]
[0 1]

In [ ]:
df['Cancelled'] = df['Cancelled'].astype(int)
df['Diverted'] = df['Diverted'].astype(int)

In [ ]:
df = pd.get_dummies(
    df,
    columns=['Airline', 'Origin', 'Destination', 'DelayReason', 'AircraftType'],
    drop_first=True
)

In [ ]:
print(df.select_dtypes(include='object').columns)

Index([], dtype='object')

In [ ]:
X = df.drop('Delayed', axis=1)
y = df['Delayed']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
print(X_train.dtypes)

Cancelled                    int64
Diverted                     int64
Distance                   float64
ScheduledDepartureHour       int32
ActualDepartureHour          int32
ScheduledArrivalHour         int32
ActualArrivalHour            int32
Airline_Delta                 bool
Airline_Southwest             bool
Airline_United                bool
Origin_DFW                    bool
Origin_JFK                    bool
Origin_LAX                    bool
Origin_ORD                    bool
Destination_JFK               bool
Destination_MIA               bool
Destination_SEA               bool
Destination_SFO               bool
DelayReason_Maintenance       bool
DelayReason_No Delay          bool
DelayReason_Weather           bool
AircraftType_Boeing 737       bool
AircraftType_Boeing 777       bool
dtype: object

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

lr = LogisticRegression(random_state=42)

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

Accuracy: 0.6346054134288551
[[132754  54394]
 [ 53427  54506]]
              precision    recall  f1-score   support

           0       0.71      0.71      0.71    187148
           1       0.50      0.50      0.50    107933

    accuracy                           0.63    295081
   macro avg       0.61      0.61      0.61    295081
weighted avg       0.64      0.63      0.63    295081

#knn

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import joblib

# Dictionary of models
models = {
    "Logistic_Regression": LogisticRegression(random_state=42),
    "Decision_Tree": DecisionTreeClassifier(random_state=42),
    "Random_Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Gaussian_Naive_Bayes": GaussianNB()
}

# Train, evaluate, and save models
for name, model in models.items():

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)

    print("=" * 50)
    print(f"{name}")
    print(f"Accuracy: {accuracy:.4f}")

    # Save model
    joblib.dump(model, f"{name}.pkl")

    print(f"{name}.pkl saved successfully!")

# Save StandardScaler
joblib.dump(scaler, "scaler.pkl")
print("\nscaler.pkl saved successfully!")

==================================================
Logistic_Regression
Accuracy: 0.6346
Logistic_Regression.pkl saved successfully!
==================================================
Decision_Tree
Accuracy: 0.6751
Decision_Tree.pkl saved successfully!
==================================================
Random_Forest
Accuracy: 0.6750
Random_Forest.pkl saved successfully!